Fix GCC 13 warning about dangling reference
It's not wrong because QOpcUaStructureDefinition::fields() returns a
QList by value, so the memory is still retained. But GCC can't know
that.

qopcuagenericstructhandlerprivate.cpp:207:21: error: possibly dangling reference to a temporary [-Werror=dangling-reference]

Change-Id: I85599ea5ca7a4b79a8bbfffd178af6426fd73f36
Reviewed-by: Frank Meerkoetter <frank.meerkoetter@basyskom.com>