Fix build: this declarative library depends on CorePrivate
opcuareaditem_p.h:12:10: fatal error: QtCore/private/qglobal_p.h: No
such file or directory

Found while making multi-subarch build. Don't ask me why this was
working before.

Change-Id: I76216ced393445a4ae2dfffd1729c0e02c9260ac
Reviewed-by: Frank Meerkoetter <frank.meerkoetter@basyskom.com>