Fix error C2362 on Windows
Initializing variables with NULL if the initialzation gets omitted
by a GOTO label in open62541.c

Upstream pull request: https://github.com/open62541/open62541/pull/5786

Change-Id: I4706e2849f49988d7057d6015c679068692fbd08
Task-number: QTBUG-113504
Reviewed-by: Frank Meerkoetter <frank.meerkoetter@basyskom.com>
(cherry picked from commit 0bb2a58bd33b63c3b274bfd872d262fa021f311b)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>