Client: Fix warning about unused capture in lambda
Found by Clang 14:

qopcuagdsclient.cpp:1813:71: error: lambda capture 'this' is not used [-Werror,-Wunused-lambda-capture]

Change-Id: I36b24183fbd041179f2ffffd17026e1ed0fc7d29
Reviewed-by: Frank Meerkoetter <frank.meerkoetter@basyskom.com>
(cherry picked from commit 15281954d8dc1057f2bf16f3b63ccb0bd356f7f3)
Reviewed-by: Marc Mutz <marc.mutz@qt.io>
Reviewed-by: Thiago Macieira <thiago.macieira@intel.com>