examples: waterpump - msvc compile fix
compiling unity builds gives:
fatal error C1017: invalid integer constant expression.

Pick-to: 6.8
Change-Id: Ifc75f1bb472322f3add0f3ff6c3559bbd10c88f1
Reviewed-by: Jannis Völker <jannis.voelker@basyskom.com>
(cherry picked from commit 6cb612adafa0b22fc03c4caebe72d53d8497efd5)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>
(cherry picked from commit 3b0e4e11ecea0d846159b0e2d31f2b246447fdb9)